# Generated by Django 4.0.4 on 2022-05-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_facebook_url_userprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='instagram_url',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
    ]
