# Generated by Django 4.0.4 on 2022-05-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_facebook_url_userprofile_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
